version: '3.8'
services:
  sequence-service:
    image: highqualitycoffee/seq_mem_spring:latest
    container_name: seq_mem_spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://seq_mem_db:3306/member_database  # MariaDB의 서비스 이름을 사용하여 연결
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks: # 네트워크 설정
      - app-network # `db`와 동일한 네트워크에 연결

  db:
    image: highqualitycoffee/seq_mem_db:latest
    container_name: seq_mem_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=member_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks: # 네트워크 설정으로 서비스 간 통신을 가능하게 함
      - app-network # 정의된 네트워크 이름
    restart: always # 컨테이너가 중단되었을 때 자동으로 재시작
    ports:
      - "3307:3306"

  phpmyadmin: # phpMyAdmin 서비스 정의
    image: phpmyadmin/phpmyadmin:latest # 최신 버전의 phpMyAdmin 이미지 사용
    container_name: phpmyadmin # phpMyAdmin 컨테이너 이름 설정
    environment: # phpMyAdmin 설정을 위한 환경 변수
      PMA_HOST: db # phpMyAdmin이 연결할 데이터베이스 서비스 이름 (위의 `db` 서비스와 연결)
      PMA_USER: root # phpMyAdmin에서 사용할 데이터베이스 사용자
      PMA_PASSWORD: root # 데이터베이스 사용자 비밀번호
    ports: # 포트 설정으로 호스트와 컨테이너 간 연결
      - "8082:80" # 호스트의 8080 포트를 phpMyAdmin의 80 포트에 매핑
    depends_on: # 컨테이너 실행 순서를 정의
      - db # phpMyAdmin이 `db` 컨테이너가 준비된 후에 실행되도록 설정
    networks: # 네트워크 설정
      - app-network # `db`와 동일한 네트워크에 연결
    restart: always # 컨테이너가 중단되었을 때 자동으로 재시작

networks:
  app-network: # 사용자 정의 네트워크를 생성
    driver: bridge # 브리지 네트워크 드라이버를 사용하여 동일 네트워크 상에서 통신 가능

volumes:
  mariadb_data: